name: Third workflows

on:
  push:
    branches: ["dev"]

jobs:
  run-first-command:
    runs-on: ubuntu-latest
    steps:
      - name: List File and copy Repo
        run: ls -a
      - uses: actions/checkout@v4
      - name: List File after Copy Repo
        run: ls -a
